apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: webservices.apps.codeform.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apps.codeform.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      additionalPrinterColumns:
        - name: Healthy
          jsonPath: .status.healthy
          type: boolean
        - name: Replicas
          jsonPath: .status.replicas
          type: integer
        - name: CPU (%)
          jsonPath: .status.cpuUtilizationPercentage
          type: integer
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                currentSpecSHA:
                  type: integer
                currentSHA:
                  type: integer
                replicas:
                  type: integer
                healthy:
                  type: boolean
                cpuUtilizationPercentage:
                  type: integer
                currentRolloutStrategy:
                  type: string
            spec:
              type: object
              properties:
                port:
                  type: integer
                image:
                  type: string
                expose:
                  type: object
                  properties:
                    host:
                      type: string
                    path:
                      type: string
                allowedClients:
                  type: array
                  items:
                    type: object
                    properties:
                      app:
                        type: string
                healthcheck:
                  type: object
                  properties:
                    path:
                      type: string
                resources:
                  type: object
                  properties:
                    min:
                      type: object
                      properties:
                        cpu:
                          type: string
                    max:
                      type: object
                      properties:
                        cpu:
                          type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: webservices
    # singular name to be used as an alias on the CLI and for display
    singular: webservice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: WebService
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ws
    - web
