apiVersion: apps.codeform.io/v1alpha1
kind: WebService
metadata:
  name: hello
spec:
  image: "docker.io/kennethreitz/httpbin"
  # image: "k8s.gcr.io/hpa-example" # "nginx:1.14.2"
  port: 80
  expose:
    host: hello.example.com
  allowedClients:
  - app: "some-allowed-client"
  - app: "some-other-client"
  healthcheck:
    path: /
  resources:
    min:
      cpu: 400m
    max:
      cpu: 800m
