apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.org.example.com
spec:
  group: org.example.com
  names:
    kind: Project
    plural: projects
    shortNames:
    - prj
    singular: project
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              environments:
                items:
                  type: string
                type: array
              quota:
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  pods:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: ctrl.declare.dev/v1
kind: Controller
metadata:
  name: projects
spec:
  children:
  - apiVersion: v1
    kind: Namespace
  - apiVersion: v1
    kind: ResourceQuota
  crdName: projects.org.example.com
  source:
    controller.jsonnet: |
      function(request) {

        local obj = request.object,

        children: [] + ( std.flattenArrays([
          [
            {
              apiVersion: 'v1',
              kind: 'Namespace',
              metadata: {
                name: obj.metadata.name + '-' + e,
              }
            },
            {
              apiVersion: 'v1',
              kind: 'ResourceQuota',
              metadata: {
                name: 'team-quota',
                namespace: obj.metadata.name + '-' + e
              },
              spec: {
                hard: {
                  cpu: obj.spec.quota.cpu,
                  memory: obj.spec.quota.memory,
                  pods: obj.spec.quota.pods
                }
              }
            },
          ] for e in obj.spec.environments ])
        )
      }
