apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: projects.org.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: org.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                quota:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                    pods:
                      type: string
                environments:
                  type: array
                  items:
                    type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: projects
    # singular name to be used as an alias on the CLI and for display
    singular: projects
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Project
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - prj
