apiVersion: org.codeform.io/v1
kind: Project
metadata:
  name: orders
spec:
  repo: https://github.com/codeformio/k8s-orders-app.git
  environments:
  - dev
  - stg
  - feature-a
  access:
    view:
    - group: orders-devs
    edit:
    - group: orders-admins-us
    - group: orders-admins-apj
  resources:
    envQuotas: { cpu: "1", memory: "2", pods: "100" }
    podDefaults:
      requests: { cpu: "1",  memory: "2"  }
      limits:   { cpu: "10", memory: "20" }

