apiVersion: apps.example.com/v1
kind: WebAPI
metadata:
  name: hello
spec:
  image: "k8s.gcr.io/hpa-example" # "nginx:1.14.2"
  port: 80
  public: true
  allowedClients:
  - app: "some-allowed-client"
  - app: "some-other-client"
  healthcheck:
    path: /
  resources:
    min:
      cpu: 400m
    max:
      cpu: 800m
