apiVersion: apps.example.com/v1
kind: WebAPI
metadata:
  name: hello
spec:
  image: "nginx:1.14.2"
  port: 80
  public: true
  allowedClients:
  - app: "some-allowed-client"
  - app: "some-other-client"
