apiVersion: ctrl.declare.dev/v1
kind: Controller
metadata:
  name: clusters
spec:
  for:
    apiVersion: k8s.example.com/v1
    kind: Cluster
  dependencies:
  - apiVersion: cluster.x-k8s.io/v1alpha3
    kind: Cluster
  - apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
  - apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
    kind: KubeadmConfigTemplate
  - apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
  - apiVersion: cluster.x-k8s.io/v1alpha3
    kind: MachineDeployment
  - apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSMachineTemplate
  source:
    controller.jsonnet: |
      function(request) {

        local obj = request.object,

        local clu = {
          "apiVersion": "cluster.x-k8s.io/v1alpha3",
          "kind": "Cluster",
          "metadata": {
            "name": obj.metadata.name,
            "namespace": "default",
          },
          "spec": {
            "clusterNetwork": {
              "pods": {
                "cidrBlocks": [
                  "192.168.0.0/16"
                ]
              }
            },
            "controlPlaneRef": {
              "apiVersion": "controlplane.cluster.x-k8s.io/v1alpha3",
              "kind": "KubeadmControlPlane",
              "name": obj.metadata.name + "-control-plane"
            },
            "infrastructureRef": {
              "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
              "kind": "AWSCluster",
              "name": obj.metadata.name
            }
          }
        },

        local awsClu = {
          "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
          "kind": "AWSCluster",
          "metadata": {
            "name": obj.metadata.name,
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "region": "us-east-1",
            "sshKeyName": "default"
          }
        },

        local kAdmCtrl = {
          "apiVersion": "controlplane.cluster.x-k8s.io/v1alpha3",
          "kind": "KubeadmControlPlane",
          "metadata": {
            "name": obj.metadata.name + "-control-plane",
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "infrastructureTemplate": {
              "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
              "kind": "AWSMachineTemplate",
              "name": obj.metadata.name + "-control-plane"
            },
            "kubeadmConfigSpec": {
              "clusterConfiguration": {
                "apiServer": {
                  "extraArgs": {
                    "cloud-provider": "aws"
                  }
                },
                "controllerManager": {
                  "extraArgs": {
                    "cloud-provider": "aws"
                  }
                }
              },
              "initConfiguration": {
                "nodeRegistration": {
                  "kubeletExtraArgs": {
                    "cloud-provider": "aws"
                  },
                  "name": "{{ ds.meta_data.local_hostname }}"
                }
              },
              "joinConfiguration": {
                "nodeRegistration": {
                  "kubeletExtraArgs": {
                    "cloud-provider": "aws"
                  },
                  "name": "{{ ds.meta_data.local_hostname }}"
                }
              }
            },
            "replicas": 3,
            "version": "v1.17.3"
          }
        },

        local ctrlMacTmpl = {
          "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
          "kind": "AWSMachineTemplate",
          "metadata": {
            "name": obj.metadata.name + "-control-plane",
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "template": {
              "spec": {
                "iamInstanceProfile": "control-plane.cluster-api-provider-aws.sigs.k8s.io",
                "instanceType": "t3.small",
                "sshKeyName": "default"
              }
            }
          }
        },

        local macDep = {
          "apiVersion": "cluster.x-k8s.io/v1alpha3",
          "kind": "MachineDeployment",
          "metadata": {
            "name": obj.metadata.name + "-md-0",
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "clusterName": obj.metadata.name,
            "replicas": obj.spec.nodeCount,
            "selector": {
              "matchLabels": null
            },
            "template": {
              "spec": {
                "bootstrap": {
                  "configRef": {
                    "apiVersion": "bootstrap.cluster.x-k8s.io/v1alpha3",
                    "kind": "KubeadmConfigTemplate",
                    "name": obj.metadata.name + "-md-0"
                  }
                },
                "clusterName": obj.metadata.name,
                "infrastructureRef": {
                  "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
                  "kind": "AWSMachineTemplate",
                  "name": obj.metadata.name + "-md-0"
                },
                "version": "v1.17.3"
              }
            }
          }
        },

        local macTmpl = {
          "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
          "kind": "AWSMachineTemplate",
          "metadata": {
            "name": obj.metadata.name + "-md-0",
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "template": {
              "spec": {
                "iamInstanceProfile": "nodes.cluster-api-provider-aws.sigs.k8s.io",
                "instanceType": "t3.small",
                "sshKeyName": "default"
              }
            }
          }
        },

        local kAdmCfgTmpl = {
          "apiVersion": "bootstrap.cluster.x-k8s.io/v1alpha3",
          "kind": "KubeadmConfigTemplate",
          "metadata": {
            "name": obj.metadata.name + "-md-0",
            "namespace": "default",
            "annotations": {
              # CAPI Cluster will adopt this resource.
              "ctrl.declare.dev/ownership": "none",
            }
          },
          "spec": {
            "template": {
              "spec": {
                "joinConfiguration": {
                  "nodeRegistration": {
                    "kubeletExtraArgs": {
                      "cloud-provider": "aws"
                    },
                    "name": "{{ ds.meta_data.local_hostname }}"
                  }
                }
              }
            }
          }
        },

        apply: [clu, awsClu, kAdmCtrl, ctrlMacTmpl, macDep, macTmpl, kAdmCfgTmpl]
      }
  
  
